
title: My Project Site
email: georgi.pandev.33@gmail.com
description: Hello!
baseurl: "" 
url: "" 
twitter_username: #
github_username:  Gpandev

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
